image: daedalusproject/base_golang_1_15:202009121604

stages:
    - test
    - deploy

unit_tests:
  stage: test
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-common-types
    - cd $GOPATH/src/github.com/a-castellano/music-manager-common-types
  script:
    - echo $GOPATH
    - pwd
    - make test

race_detector:
  stage: test
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-common-types
    - cd $GOPATH/src/github.com/a-castellano/music-manager-common-types
  script:
    - make race

memory_sanitizer:
  stage: test
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-common-types
    - cd $GOPATH/src/github.com/a-castellano/music-manager-common-types
  script:
    - make msan

code_coverage:
  stage: test
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-common-types
    - cd $GOPATH/src/github.com/a-castellano/music-manager-common-types
  script:
    - make coverage
  artifacts:
    name: "coverage-$CI_PIPELINE_ID"
    paths:
      - coverage.html
      - cover
    expire_in: 1 hour
  coverage: /total:\s+.+\s(\d+\.\d+?)%$/

code_coverage_report:
  stage: test
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-common-types
    - cd $GOPATH/src/github.com/a-castellano/music-manager-common-types
  script:
    - make coverhtml
  only:
  - master

lint_code:
  stage: test
  before_script:
    - export CC=/usr/bin/clang
    - export GOPATH="$(pwd)/go"
    - mkdir -p "$(pwd)/go"
    - go env -w GOPATH="$(pwd)/go"
    - mkdir -p $GOPATH/src/github.com/a-castellano
    - ln -s ${CI_PROJECT_DIR} $GOPATH/src/github.com/a-castellano/music-manager-common-types
    - cd $GOPATH/src/github.com/a-castellano/music-manager-common-types
  script:
    - make lint

pages:
  stage: deploy
  image: daedalusproject/base:202001111126
  script:
  - cp coverage.html public/
  artifacts:
    paths:
    - public
  only:
  - master
